### ISSUE TITLE
LTS 2.18 branch failing

### ISSUE THREAD

**Issue by boydkr** [khorus/ember-accordion#15]
Does it need the polyfill to support Ember 2.x?
https://github.com/rwjblue/ember-angle-bracket-invocation-polyfill

See comment in issue:
https://github.com/rwjblue/ember-angle-bracket-invocation-polyfill/issues/23#issuecomment-404227593
although that's from almost a  year ago.  I couldn't find anything else that seems relevant

**Comment by chbonser** [comment]
Yes we needed the polyfill. Master is now passing.
