### ISSUE TITLE
liquid-fire required by addon but not installed

### ISSUE THREAD

**Issue by boydkr** [khorus/ember-accordion#2]
Installing add-on is successful, but there is an error for "unknown helper `liquid-fire`".  Installing liquid-fire through ember resolves the issue.

**Comment by chbonser** [comment]
I actually intend to drop the liquid-fire dependency as it is a pretty heavy handed way to add some simple animations.  I hope to get to that this week.

**Comment by chbonser** [comment]
On further reflection, let's stick with the liquid-fire dependency for now. I'll merge the PR.
