### ISSUE TITLE
Error installing the addon

### ISSUE THREAD

**Issue by kurocygnus** [khorus/ember-accordion#46]
Tried to install with ember install but got this error.

error broccoli-postcss@3.5.3: The engine "node" is incompatible with this module. Expected version "^4.5 || ^6 || ^7 || ^8 || ^9 || ^10". Got "12.13.1"
error Found incompatible module.

**Comment by chbonser** [comment]
@kurocygnus sorry for your trouble. Which version of Ember is your project using?

The 0.7.0 release upgraded this project to Ember 3.14 which in theory supports Node 12 (my projects are still using Node 10). See [Ember's Node support matrix](https://github.com/ember-cli/ember-cli/blob/master/docs/node-support.md).

Also another clue that might help you... This addon does not add the `broccoli-postcss` dependency to your app. Try running `yarn why broccoli-postcss` to see why it is in your dependencies.

**Comment by chbonser** [comment]
@kurocygnus I'm going to close this but please reply if you need further help.
